# Generated by Django 4.1.3 on 2023-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_categoria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
